services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: internet-speed-db

    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${SQLSERVER_PWD}"
      MSSQL_PID: "Developer"

    ports:
      - "1433:1433"

    volumes:
      - mssql-data:/var/opt/mssql
      - ./sql/00_DDL.sql:/init/00_DDL.sql:ro

    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd", "-C", "-S", "localhost", "-U", "sa", "-P", "${SQLSERVER_PWD}", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

    restart: unless-stopped
